site_name: "CRTP"
site_author: "Tirtha Mandal"
copyright: ""

repo_name: tirtha-mandal
repo_url: https://tirtha-mandal/
edit_uri: tree/master/docs

nav:
  - Home: index.md
  - CRTP: 
      - Domain Enumation: crtp/domain-enum.md
  - Web App:
      - Interview Questions: web/interview.md    


theme:
  name: material
  palette:
    primary: teal
    accent: teal
  # logo: assets/now-logo.svg
  # favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  # features:
  #   - header.autohide

# extra_css:
#     - assets/css/custom.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - admonition
  - codehilite
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
